{
 "title": "RabbitMQ Overview Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(process_uptime_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\", job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_connections{instance=\"$node\",job=\"rabbitmq\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "channels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_channels{instance=\"$node\",job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "queues",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_queues{instance=\"$node\",job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "consumers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_consumers{instance=\"$node\",job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "exchanges",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_exchanges{instance=\"$node\",job=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "Queued messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_messages_ready{instance=\"$node\", job=\"rabbitmq\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "rabbitmq_messages_unacknowledged{instance=\"$node\",job=\"rabbitmq\"}",
     "legendFormat": "unacked"
    },
    {
     "expr": "rabbitmq_messages_unacknowledged{instance=\"$node\",job=\"rabbitmq\"} + rabbitmq_messages_ready{instance=\"$node\", job=\"rabbitmq\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Message rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_messages_published_total{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "Publish"
    },
    {
     "expr": "irate(rabbitmq_messages_confirmed_total{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "Publish Confirm"
    },
    {
     "expr": "irate(rabbitmq_messages_delivered_total{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "deliver"
    },
    {
     "expr": "irate(rabbitmq_messages_delivered_no_ack_total{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "deliver_noack"
    },
    {
     "expr": "irate(rabbitmq_messages_redelivered_total{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "redeliver"
    },
    {
     "expr": "irate(rabbitmq_messages_returned_total{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Disk IO - irate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_queues_disk_reads{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "reads"
    },
    {
     "expr": "irate(rabbitmq_queues_disk_writes{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Disk IO rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_queues_disk_reads{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(rabbitmq_queues_disk_writes{instance=\"$node\", job=\"rabbitmq\"}[5m])",
     "legendFormat": "writes"
    }
   ]
  }
 ]
}