{
 "title": "RabbitMQ Queues Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(process_uptime_seconds, instance)"
   },
   {
    "name": "vhost",
    "query": "label_values(rabbitmq_queue_durable, vhost)"
   },
   {
    "name": "queue",
    "query": "label_values(rabbitmq_queue_durable, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Durable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_queue_durable{queue=\"$queue\", job=\"rabbitmq\", vhost=\"$vhost\",instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Auto-delete",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_queue_auto_delete{instance=\"$node\",vhost=\"$vhost\",queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Exclusive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_queue_exclusive{instance=\"$node\",vhost=\"$vhost\",queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_queue_state{instance=\"$node\",vhost=\"$vhost\",queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Cousumers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{instance=\"$node\",vhost=\"$vhost\",queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "ready"
    },
    {
     "expr": "rabbitmq_queue_messages_unacknowledged{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "unack"
    },
    {
     "expr": "rabbitmq_queue_messages{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "total"
    },
    {
     "expr": "rabbitmq_queue_messages_ready_ram{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "ready_ram"
    },
    {
     "expr": "rabbitmq_queue_messages_unacknowledged_ram{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "unack_ram"
    },
    {
     "expr": "rabbitmq_queue_messages_ram{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "total_ram"
    },
    {
     "expr": "rabbitmq_queue_messages_persistent{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "persistent"
    }
   ]
  },
  {
   "title": "Messages rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages_published_total{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}[5m])",
     "legendFormat": "published"
    },
    {
     "expr": "irate(rabbitmq_queue_messages_confirmed_total{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}[5m])",
     "legendFormat": "confirmed"
    },
    {
     "expr": "irate(rabbitmq_queue_messages_delivered_total{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}[5m])",
     "legendFormat": "delivered"
    },
    {
     "expr": "irate(rabbitmq_queue_messages_delivered_no_ack_total{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}[5m])",
     "legendFormat": "delivered_no_ack"
    },
    {
     "expr": "irate(rabbitmq_queue_messages_redelivered_total{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}[5m])",
     "legendFormat": "redelivered"
    },
    {
     "expr": "irate(rabbitmq_queue_messages_returned_total{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}[5m])",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "Queued Messages Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_message_bytes{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "total bytes"
    },
    {
     "expr": "rabbitmq_queue_message_bytes_ready{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "ready bytes"
    },
    {
     "expr": "rabbitmq_queue_message_bytes_unacknowledged{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "unack  bytes"
    },
    {
     "expr": "rabbitmq_queue_message_bytes_ram{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "ram bytes"
    },
    {
     "expr": "rabbitmq_queue_message_bytes_persistent{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "persistent bytes"
    }
   ]
  },
  {
   "title": "Queue memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_memory{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_disk_reads{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "rabbitmq_queue_disk_writes{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "writes"
    },
    {
     "expr": "rabbitmq_queue_disk_size_bytes{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "disk size bytes"
    }
   ]
  },
  {
   "title": "Consumer utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumer_utilisation{instance=\"$node\",job=\"rabbitmq\",vhost=\"$vhost\",queue=\"$queue\"}",
     "legendFormat": "consumer utilisation"
    }
   ]
  }
 ]
}