{
 "title": "RabbitMQ Erlang VM & OTP Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(process_uptime_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "smp_support",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "erlang_vm_smp_support{instance=\"$node\",job=\"rabbitmq\"}"
      }
     ]
    },
    {
     "title": "threads",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "erlang_vm_threads{instance=\"$node\",job=\"rabbitmq\"}"
      }
     ]
    },
    {
     "title": "threads",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "erlang_vm_time_correction{instance=\"$node\",job=\"rabbitmq\"}"
      }
     ]
    },
    {
     "title": "ets_limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_ets_limit{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "ets_limit"
      },
      {}
     ]
    },
    {
     "title": "logical_processors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_logical_processors{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "logical_processors"
      },
      {
       "expr": "erlang_vm_logical_processors_available{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "logical_processors_available"
      },
      {
       "expr": "erlang_vm_logical_processors_online{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "logical_processors_online"
      }
     ]
    },
    {
     "title": "port_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_port_count{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "port_count"
      },
      {
       "expr": "erlang_vm_port_limit{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "port_limit"
      }
     ]
    },
    {
     "title": "process_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_process_count{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "process_count"
      },
      {
       "expr": "erlang_vm_process_limit{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "process_limit"
      }
     ]
    },
    {
     "title": "schedulers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_schedulers{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "schedulers"
      },
      {
       "expr": "erlang_vm_schedulers_online{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "schedulers_online"
      }
     ]
    },
    {
     "title": "thread_pool_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_thread_pool_size{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "schedulers"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_statistics_bytes_output_total{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "bytes_output"
      },
      {
       "expr": "erlang_vm_statistics_bytes_received_total{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "bytes_received"
      }
     ]
    },
    {
     "title": "context_switches",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\",job=\"rabbitmq\"}[5m])",
       "legendFormat": "context_switches"
      }
     ]
    },
    {
     "title": "gc rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\",job=\"rabbitmq\"}[5m])",
       "legendFormat": "gc rate"
      }
     ]
    },
    {
     "title": "gc bytes rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\",job=\"rabbitmq\"}[5m])",
       "legendFormat": "gc bytes rate"
      }
     ]
    },
    {
     "title": "gc words rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_garbage_collection_words_reclaimed{instance=\"$node\",job=\"rabbitmq\"}[5m])",
       "legendFormat": "gc words rate"
      }
     ]
    },
    {
     "title": "reductions rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\",job=\"rabbitmq\"}[5m])",
       "legendFormat": "reductions rate"
      }
     ]
    },
    {
     "title": "run_queues_length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "run_queues_length"
      }
     ]
    },
    {
     "title": "runtime",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_statistics_runtime_milliseconds{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "runtime"
      },
      {
       "expr": "erlang_vm_statistics_wallclock_time_milliseconds{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "wallclock_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "atom_bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_memory_atom_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"free\"}",
       "legendFormat": "atom_bytes_free"
      },
      {
       "expr": "erlang_vm_memory_atom_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"used\"}",
       "legendFormat": "atom_bytes_used"
      }
     ]
    },
    {
     "title": "atom_bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_memory_bytes_total{instance=\"$node\",job=\"rabbitmq\",kind=\"system\"}",
       "legendFormat": "memory_bytes_system"
      },
      {
       "expr": "erlang_vm_memory_bytes_total{instance=\"$node\",job=\"rabbitmq\",kind=\"processes\"}",
       "legendFormat": "memory_bytes_process"
      }
     ]
    },
    {
     "title": "dets&ets tables",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_dets_tables{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "dets_tables"
      },
      {
       "expr": "erlang_vm_ets_tables{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "ets_tables"
      }
     ]
    },
    {
     "title": "processes_bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_memory_processes_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"free\"}",
       "legendFormat": "processes_bytes_free"
      },
      {
       "expr": "erlang_vm_memory_processes_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"used\"}",
       "legendFormat": "processes_bytes_used"
      }
     ]
    },
    {
     "title": "system_bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"atom\"}",
       "legendFormat": "system_bytes_atom"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"binary\"}",
       "legendFormat": "system_bytes_binary"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"code\"}",
       "legendFormat": "system_bytes_code"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"ets\"}",
       "legendFormat": "system_bytes_ets"
      },
      {
       "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\",job=\"rabbitmq\",usage=\"other\"}",
       "legendFormat": "system_bytes_other"
      }
     ]
    }
   ]
  },
  {
   "title": "Mnesia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "locks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_mnesia_held_locks{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "held_locks"
      },
      {
       "expr": "erlang_mnesia_lock_queue{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "lock_queue"
      }
     ]
    },
    {
     "title": "transaction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_mnesia_transaction_participants{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "transaction_participants"
      },
      {
       "expr": "erlang_mnesia_transaction_coordinators{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "transaction_coordinators"
      }
     ]
    },
    {
     "title": "transaction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "erlang_mnesia_failed_transactions{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "failed"
      },
      {
       "expr": "erlang_mnesia_committed_transactions{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "erlang_mnesia_logged_transactions{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "logged"
      },
      {
       "expr": "erlang_mnesia_restarted_transactions{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "restarted"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "fds",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$node\",job=\"rabbitmq\"}"
      },
      {
       "expr": "process_max_fds{instance=\"$node\",job=\"rabbitmq\"}"
      }
     ]
    },
    {
     "title": "uptime",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "process_start_time_seconds{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "start_time"
      },
      {
       "expr": "process_uptime_seconds{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "uptime"
      }
     ]
    },
    {
     "title": "threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "process_threads_total{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "start_time"
      }
     ]
    },
    {
     "title": "process memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "virtual"
      },
      {
       "expr": "process_resident_memory_bytes{instance=\"$node\",job=\"rabbitmq\"}",
       "legendFormat": "resident"
      }
     ]
    },
    {
     "title": "cpu time rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 1, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=\"$node\",job=\"rabbitmq\",kind=\"utime\"}[5m])",
       "legendFormat": "virtual"
      },
      {
       "expr": "irate(process_cpu_seconds_total{instance=\"$node\",job=\"rabbitmq\",kind=\"stime\"}[5m])",
       "legendFormat": "resident"
      }
     ]
    }
   ]
  }
 ]
}