{
 "title": "RabbitMQ MnesiaTables Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(process_uptime_seconds, instance)"
   },
   {
    "name": "table",
    "query": "label_values(rabbitmq_mnesia_table_read_only, table)"
   }
  ]
 },
 "panels": [
  {
   "title": "ReadOnly",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_read_only{instance=\"$node\",table=\"$table\"}"
    }
   ]
  },
  {
   "title": "NodeLocal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_local_content{instance=\"$node\",table=\"$table\"}"
    }
   ]
  },
  {
   "title": "Majority Required",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_majority_required{instance=\"$node\",table=\"$table\"}"
    }
   ]
  },
  {
   "title": "Copies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_disc_copies{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "disc_copy nodes"
    },
    {
     "expr": "rabbitmq_mnesia_table_disc_only_copies{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "disc_only_copies"
    },
    {
     "expr": "rabbitmq_mnesia_table_master_nodes{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "master_nodes"
    },
    {
     "expr": "rabbitmq_mnesia_table_ram_copies{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "ram_copies"
    }
   ]
  },
  {
   "title": "Memory/Disk Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_memory_bytes{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "memory_bytes"
    },
    {
     "expr": "rabbitmq_mnesia_table_disk_size_bytes{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "disk_size_bytes"
    }
   ]
  },
  {
   "title": "Records Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_mnesia_table_records_count{instance=\"$node\",table=\"$table\"}",
     "legendFormat": "records_count"
    }
   ]
  }
 ]
}